name: zruchnist_v2
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  very_good_analysis: ^6.0.0
  shared_preferences: ^2.2.3
  talker: ^4.2.4
  gap: ^3.0.1
  dio: ^5.4.3
  equatable: ^2.0.5
  auto_route: ^9.2.0
  json_annotation: ^4.9.0
  injectable: ^2.4.2
  get_it: ^7.7.0
  retrofit: ^4.1.0
  retrofit_generator: ^9.1.1
  auto_route_generator: ^9.0.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  mockito: ^5.4.4
  bloc_test: ^9.1.7
  intl: ^0.19.0
  uuid: ^4.5.0
  path: ^1.9.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.1
  build_runner: ^2.4.12
  mocktail: ^1.0.4


flutter:


  uses-material-design: true

 