name: presentation
description: "Presentation layer"
environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  auto_route: ^9.2.0
  bloc_test: ^9.1.7
  intl: ^0.19.0
  gap: ^3.0.1
  domain:
    path: ../domain
  core:
    path: ../core

dev_dependencies:
  build_runner: ^2.4.12
  auto_route_generator: ^9.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
