name: app
description: "Zruchnist V2 main app entry"
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.3.0
  talker_flutter: ^4.2.4
  get_it: ^7.7.0

  core:
    path: ../core
  domain:
    path: ../domain
  data:
    path: ../data
  presentation:
    path: ../presentation

dev_dependencies:
  flutter_test:
    sdk: flutter
