name: core
description: "Core utilities"
environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  talker: ^4.2.4
  get_it: ^7.7.0
  uuid: ^4.5.0
  path: ^1.9.0
  path_provider: ^2.1.4

dev_dependencies:
  build_runner: ^2.4.12
  very_good_analysis: ^6.0.0
