name: firebase
description: "Firebase integrations for Zruchnist"
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4


dev_dependencies:
  very_good_analysis: ^6.0.0
