name: domain
description: "Business logic and use cases"
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  core:
    path: ../core

dev_dependencies:
  very_good_analysis: ^6.0.0
